name: Stats

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests gitpython

      - name: Run Script
        env:
          API_KEY: ${{ variables.API_KEY }}
        run: python ./notificate/stats.py
